{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "239a13ba-92d8-4d5b-85d9-e53b89a2e70b",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Tiny interactive app"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9b76e197-8262-4787-ae62-da3e6a8abe88",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-09-18 16:31:23.154 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.155 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.250 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /Users/ms/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-09-18 16:31:23.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.251 No runtime found, using MemoryCacheStorageManager\n",
      "2025-09-18 16:31:23.252 No runtime found, using MemoryCacheStorageManager\n",
      "2025-09-18 16:31:23.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.306 Session state does not function when running a script without `streamlit run`\n",
      "2025-09-18 16:31:23.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.309 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.309 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.321 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.321 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.321 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-18 16:31:23.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from pathlib import Path\n",
    "import pandas as pd\n",
    "import streamlit as st\n",
    "\n",
    "# --- locate repo root no matter where we run from ---\n",
    "def find_repo_root(start: Path = Path.cwd()) -> Path:\n",
    "    for p in [start] + list(start.parents):\n",
    "        if (p / \"data\" / \"processed\").exists() and (p / \"projects\").exists():\n",
    "            return p\n",
    "    return start\n",
    "\n",
    "ROOT = find_repo_root()\n",
    "PROCESSED = ROOT / \"data\" / \"processed\"\n",
    "WIDE = PROCESSED / \"kpi_chronic_wide_all_levels.csv\"\n",
    "LONG = PROCESSED / \"kpi_chronic_long_all_levels.csv\"\n",
    "\n",
    "st.set_page_config(page_title=\"CA Chronic Absenteeism (Replica)\", layout=\"wide\")\n",
    "st.title(\"California Chronic Absenteeism — Dashboard Replica\")\n",
    "\n",
    "# --- load data ---\n",
    "@st.cache_data\n",
    "def load_dfs():\n",
    "    wide = pd.read_csv(WIDE)\n",
    "    long = pd.read_csv(LONG)\n",
    "    # basic typing\n",
    "    for df in (wide, long):\n",
    "        if \"cohort\" in df.columns:\n",
    "            df[\"cohort\"] = pd.to_numeric(df[\"cohort\"], errors=\"coerce\")\n",
    "    return wide, long\n",
    "\n",
    "try:\n",
    "    wide, long = load_dfs()\n",
    "except Exception as e:\n",
    "    st.error(f\"Could not load processed files from {PROCESSED}. Error: {e}\")\n",
    "    st.stop()\n",
    "\n",
    "# --- controls ---\n",
    "\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "    level = st.selectbox(\"Geography\", [\"district\",\"county\",\"state\"])\n",
    "with col2:\n",
    "    metric = st.selectbox(\"Metric\", [\"chronic_absent_rate\",\"non_chronic_rate\",\"gap_vs_all\"])\n",
    "\n",
    "# Optional geo filters\n",
    "if level == \"district\":\n",
    "    dists = sorted(wide.loc[wide[\"geo_level\"]==\"district\",\"district_name\"].dropna().unique())\n",
    "    district = st.selectbox(\"District (optional)\", [\"(All)\"] + dists)\n",
    "else:\n",
    "    district = \"(All)\"\n",
    "\n",
    "if level == \"county\":\n",
    "    cntys = sorted(wide.loc[wide[\"geo_level\"]==\"county\",\"county_name\"].dropna().unique())\n",
    "    county = st.selectbox(\"County (optional)\", [\"(All)\"] + cntys)\n",
    "else:\n",
    "    county = \"(All)\"\n",
    "\n",
    "# --- filter data for view ---\n",
    "f = long[(long[\"metric\"] == metric) & (long[\"geo_level\"] == level)].copy()\n",
    "\n",
    "if level == \"district\" and district != \"(All)\":\n",
    "    f = f[f[\"district_name\"] == district]\n",
    "if level == \"county\" and county != \"(All)\":\n",
    "    f = f[f[\"county_name\"] == county]\n",
    "\n",
    "# Show quick summary\n",
    "left, right = st.columns(2)\n",
    "with left:\n",
    "    st.metric(\"Rows\", len(f))\n",
    "with right:\n",
    "    if \"value\" in f.columns:\n",
    "        st.metric(\"Avg value\", round(float(f[\"value\"].mean()), 4) if not f.empty else 0.0)\n",
    "\n",
    "st.dataframe(f.sort_values(\"value\", ascending=False).reset_index(drop=True))\n",
    "\n",
    "st.caption(f\"Data directory: {PROCESSED}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2715e908-1342-4e4d-a4dc-6b2caaf43695",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
